# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


#Phil's store, tables, and games creation
Store.create(name: "Phil's Phabulous Phantasy Phactory", location: "5th street by that old tree", description: "It's...definitely a place")
GameTable.create(store_id: 1, table_name: "Phear The Reaper", seats_available: 6)
GameTable.create(store_id: 1, table_name: "Phorget Your worries", seats_available: 6)
GameTable.create(store_id: 1, table_name: "Phun Phor All", seats_available: 8)
GameTable.create(store_id: 1, table_name: "Phree Phor All", seats_available: 4)
GameTable.create(store_id: 1, table_name: "Phool's Gold", seats_available: 7)
Game.create(store_id: 1, name: "Phantasy Realm", description: "Players go on one of four quests, racing against each other to satisfy the victory conditions. Each turn, a hero can move rapidly about or search the areas of the board. While searching, the hero will receive an encounter, drawn and run by another player, or play through an encounter scenario (for named areas of the board). Results can help or hinder each hero by changing stats and equipment and magic. Players can also encounter other players. Combat is by competing dice rolls, modified by stats and equipment modifiers.", min_players: 2, max_players: 4, min_playtime: 60, max_playtime: 60, link_url: "https://boardgamegeek.com/boardgame/5877/phantasy-realm", photo_url: "https://cf.geekdo-images.com/imagepage/img/yCjGXzpt8KKuJQ9WvODXwhOEysU=/fit-in/900x600/filters:no_upscale()/pic22098.jpg")
Game.create(store_id: 1, name: "Philanthropoly", description: "Philanthropoly is a card based game where players negotiate and trade with other players to collect action cards to build factories, railroad and/or ports to increase the value of the various companies. Stocks in the various companies can be bought and sold depending on the players speculations and cash flow needs. Cash is earned by the play of production cards, with the type of production dependent on what natural resource, region or city card is played in conjunction. The ultimate goal of the game is to earn enough money to buy (donate) to various philanthropic causes. The most philanthropic player at the end of the game wins.", min_players: 2, max_players: 6, min_playtime: 150, max_playtime: 300, link_url: "https://boardgamegeek.com/boardgame/231340/philanthropoly", photo_url: "https://cf.geekdo-images.com/imagepage/img/2UiMbfni5B_4fLKQtKaU8D68fXU=/fit-in/900x600/filters:no_upscale()/pic3660122.gif")
Game.create(store_id: 1, name: "Philadelphia", description: "Philadelphia is a TCG-like card game where players aim to develop the advertising agency they work for. Earn money by placing diverse and colorful advertising cards with unique abilities, and aim for combos by combining effects to get large rewards.

Earned money can be used to efficiently collect sets of cards with the same color/industry, which you can present to investors as an attractive set of advertisements, raising your reputation and gain victory points.
Will you be able to hold down rival employees, and stand victorious?", min_players: 2, max_players: 4, min_playtime: 30, max_playtime: 60, link_url: "https://boardgamegeek.com/boardgame/292863/philadelphia", photo_url: "https://cf.geekdo-images.com/imagepage/img/3C_OqM_-j65sYfiCzL5wUCLIvh0=/fit-in/900x600/filters:no_upscale()/pic5050826.jpg")
Game.create(store_id: 1, name: "Philately", description: "A Monopoly clone stamp collecting game. There are 4 sets of 40 different stamps plus 10 spares. Players roll the die and move around the complex track, buying, selling, swapping, collecting, inheriting stamps or gaining cash. Display your set in an album as you go. No designer is named, but my box is signed by Tina & Stef (?) Dixon.
The stamps are nice.", min_players: 2, max_players: 4, min_playtime: 90, max_playtime: 90, link_url: "https://boardgamegeek.com/boardgame/2900/philately", photo_url: "https://cf.geekdo-images.com/imagepage/img/1zaunEK8p3zES-O8_6-aHAa417M=/fit-in/900x600/filters:no_upscale()/pic3051410.jpg")
Game.create(store_id: 1, name: "Dane and Phil's Truth Bombs", description: "In the party game Dan and Phil's Truth Bombs, you're going to write something about everyone else at the table, and they're going to write stuff about you. Can you guess who said what?", min_players: 4, max_players: 8, min_playtime: 20, max_playtime: 20, link_url: "https://boardgamegeek.com/boardgame/238329/dan-and-phils-truth-bombs", photo_url: "https://cf.geekdo-images.com/imagepagezoom/img/WJhEz4HEtnZu8HBWwKza6FQ2uf8=/fit-in/1200x900/filters:no_upscale()/pic3812480.jpg")
#  Game.create(store_id: 1, name: "", description: "", min_players: , max_players: , min_playtime: , max_playtime: , link_url: "", photo_url: "")



Store.create(name: "Lizard's Lair", location: "Southeast-northwest of town, just past the barn", description: "Significantly smaller than a dragon's lair")
GameTable.create(store_id: 2, table_name: "Mini Table 1", seats_available: 4)
GameTable.create(store_id: 2, table_name: "Mini Table 2", seats_available: 4)
GameTable.create(store_id: 2, table_name: "The Great Beyond", seats_available: 8)
Game.create(store_id: 2, name: "The Battle of Lizard", description: "In The Battle of Lizard, a.k.a. 蜥蓋, players each control a group of lizards on an island competing for survival — long-term survival, that is, because when breeding time arrives, these male lizards (Uta stansburiana) will fight one another for land and the right to reproduction. To succeed, you need to block others to keep them from reproducing!", min_players: 2, max_players: 6, min_playtime: 20, max_playtime: 40, link_url: "https://boardgamegeek.com/boardgame/269731/battle-lizard", photo_url: "https://cf.geekdo-images.com/original/img/5UB3a05fBlgACtNfKN7WtrCAtt8=/0x0/pic4885364.png")
Game.create(store_id: 2, name: "Lords, Ladies & Lizards: The Adventure Game", description: "Up to six Players get a chance to create and develop Characters through a complex journey that involves strategy, economics, politics and war! Players are able to play as either a Lord, a Lady or a Lizard, each with unique properties and leveling bonuses. Over the span of many game years, players will face personal struggles with jealousy and greed, deceit and rage! They will travel across three continents by land, by sea and by air, clearing the way of treacherous monsters. Players must choose which path to take... the way of the warrior? Or the lavish life of the landlord? They can build wealth and recognition through Theatres and entertainment. Or buy and trade treasures and build kingdoms that will rise and fall! They will be forced into war against one other all for the right to reign supreme! But there will only be one winner and that is the one who defeats the Dragon! Do YOU have what it takes to defeat the Dragon!?", min_players: 2, max_players: 6, min_playtime: 120, max_playtime: 180, link_url: "https://boardgamegeek.com/boardgame/102706/lords-ladies-lizards-adventure-game", photo_url: "https://cf.geekdo-images.com/imagepage/img/ak4Vr--YCzc_ezmiFa62Zd3U0VE=/fit-in/900x600/filters:no_upscale()/pic1166275.jpg")
Game.create(store_id: 2, name: "Terrible Lizards", description: "In Terrible Lizards you build your own dinosaur and fight against the reptile of your opponent. All actions including the dino parts are represented in the play of cards.", min_players: 2, max_players: 4, min_playtime: 20, max_playtime: 60, link_url: "https://boardgamegeek.com/boardgame/178610/terrible-lizards", photo_url: "https://cf.geekdo-images.com/imagepage/img/MWfJboXEL6FIoiPr0w3LFyuZAkc=/fit-in/900x600/filters:no_upscale()/pic2692626.jpg")
Game.create(store_id: 2, name: "Thrilling Expeditions: Valley of the Thunder Lizard ", description: "Thrilling Expeditions: Valley of the Thunder Lizard allows players to play big game hunters in a lost valley populated with creatures from before the rise of man, or have their pirates going ashore on an island where Neanderthals battle Saurians, or time traveling tourists suddenly stranded in Earth’s distant past.", min_players: 1, max_players: 6, min_playtime: 60, max_playtime: 90, link_url: "https://boardgamegeek.com/boardgameexpansion/36327/thrilling-expeditions-valley-thunder-lizard", photo_url: "https://cf.geekdo-images.com/imagepage/img/MVr_jc8ZKyCZ-bGa86CeWRtJp7g=/fit-in/900x600/filters:no_upscale()/pic329991.jpg")
Game.create(store_id: 2, name: "Lickin' Lizards ", description: "A rotating base contains bug or spider disks. Each player has a plastic lizard with an 'Elastomeric' tongue (patents no. 4,369,284 and 4,618,213) which can stretch to 750% of its normal length. Try to collect disks using the sticky, stretchy tongue. Three different variations are included.", min_players: 2, max_players: 4, min_playtime: 20, max_playtime: 40, link_url: "https://boardgamegeek.com/boardgame/6570/lickin-lizards", photo_url: "https://cf.geekdo-images.com/imagepage/img/a56dLg7vz-mgqCoFdMgKraaqHTw=/fit-in/900x600/filters:no_upscale()/pic1975881.jpg")
#  Game.create(store_id: 2, name: "", description: "", min_players: , max_players: , min_playtime: , max_playtime: , link_url: "", photo_url: "")


Store.create(name: "Billy-Bob's Gaming Emporeum", location: "Not there, over here", description: "Board games in the front, fishin' supplies out back")
GameTable.create(store_id: 3, table_name: "Fish Deboning Table", seats_available: 4)
GameTable.create(store_id: 3, table_name: "Master Baiting Station", seats_available: 4)
GameTable.create(store_id: 3, table_name: "The Gross Table", seats_available: 3)
Game.create(store_id: 3, name: "Gone Fishing!", description: "One player takes the role of the two anglers and tries to catch as many fish as possible. The other player takes the role of the fish and with bluff and skill tries to hinder the anglers from catching fish. The angler player decides where to fish, but must do so in the dark (that is, he cannot really see where the fish are), as the fish cards are placed face down. Because of this, he does not know whether he is catching a fish or garbage. Also, when he is lucky enough to catch a fish, he will not know until he lands it how valuable it is. With clever movement of his fish, the fish player tries to get garbage and small fish onto the anglers hooks.", min_players: 2, max_players: 2, min_playtime: 40, max_playtime: 60, link_url: "https://boardgamegeek.com/boardgame/16226/gone-fishing", photo_url: "https://cf.geekdo-images.com/imagepagezoom/img/agk_dDlW-2P9kGE8lU84kORfmtY=/fit-in/1200x900/filters:no_upscale()/pic74873.jpg")
Game.create(store_id: 3, name: "Flip & Fish", description: "Flip & Fish is a fast paced, competitive 2-4 player of dexterity, tactics and luck. The goal is to be the first player to catch the required number of trophy fish, which varies by player count.

Players take turns rolling or flicking a D12 dice from their jetty towards the cards in the middle, trying to get as close as possible to a target card. When the dice stops, a fish is caught if the dice roll (along with any bonuses) is equal or higher to the catch rate of the closest fish. Players can also use caught fish as bait, and items from the Bait & Tackle shop to increase their chances of catching fish. The game is fast to learn, but offers strategic options as players become more familiar with the game.", min_players: 2, max_players: 4, min_playtime: 5, max_playtime: 30, link_url: "https://boardgamegeek.com/boardgame/290500/flip-fish", photo_url: "https://cf.geekdo-images.com/imagepage/img/JX2W3Wz_4IssXVW_ip_Krbguge4=/fit-in/900x600/filters:no_upscale()/pic4991972.jpg")
Game.create(store_id: 3, name: "Fish 'n' Flips", description: "Fish 'n' Flips is a game about maritime animals caught in fishing nets as bycatch. Players can compete or cooperate in freeing as many as possible of them. The animals are laid out in rows and columns. On a turn, a player can play one of their two action cards. These cards can exchange positions or flip a card so the animal looks the opposite way. When several of the same animals are looking in the same direction, they will escape from the net, while any animals on top of them will slide down (tetris-style), which may lead to other groups of animals being able to escape. After each turn, another animal is added at the top of each column. When a column is seven cards high, all players lose. When all animal cards have been played, players can compare how many animals were left in the net (cooperative mode) or how many they freed (competitive mode).", min_players: 1, max_players: 6, min_playtime: 15, max_playtime: 30, link_url: "https://boardgamegeek.com/boardgame/288533/fish-n-flips", photo_url: "https://cf.geekdo-images.com/imagepagezoom/img/Z4N2lz56fKpGfwQclTKNeF-HcgI=/fit-in/1200x900/filters:no_upscale()/pic4944232.jpg")
#  Game.create(store_id: 3, name: "", description: "", min_players: , max_players: , min_playtime: , max_playtime: , link_url: "", photo_url: "")
#  Game.create(store_id: 3, name: "", description: "", min_players: , max_players: , min_playtime: , max_playtime: , link_url: "", photo_url: "")
#  Game.create(store_id: 3, name: "", description: "", min_players: , max_players: , min_playtime: , max_playtime: , link_url: "", photo_url: "")
